### PR TITLE
Rewrite schema parser

### LINKED ISSUE #24: Write new schema attribute parser
The schema attribute parser will have to be rewritten to conform to the new schema format. The new `SchemaAttributes` format is as follows:
```js
{
    "tags": [ /*array of tags*/ ],
    "tagAttributes": {/*tag*/: {/*attribute*/: /*value or [array of values]*/}},
    "tagUnitClasses": {/*tag*/: [ /*array of unit classes*/ ]},
    "unitClasses": {/*unitClassName*/: [ /*array of units*/ ]},
    "unitClassAttributes": {/*unitClassName*/: {/*attribute*/: /*value or [array of values]*/}},
    "unitAttributes": {/*unitName*/: [ /*array of attributes*/ ]},
    "unitModifiers" {/*unitModifierType/: [ /*array of unit modifiers*/ ]},
}
```

### PR DESCRIPTION
**Pull request by happy5214**
This branch completely rewrites the schema parsing code and redoes the internal interface of the `SchemaAttributes` object, along with supporting the new HED 3 schema specification.

More tests still need to be written, and this depends on the `unitAttribute` property being added to the schema.

Fixes #24

### CODE REVIEW

**Comment by VisLab** [comment]
I was wondering about the requirement that unitAttribute be added.  First of all it would be called unitProperty.  Secondly, the schema that have been released on hedxml can not be changed. They will be in the old format. They will also not have unitProperty. This will be up through HED8.0.0-alpha.2.   I am assuming that there will be a cutoff of versions?

**Comment by happy5214** [comment]
> I was wondering about the requirement that unitAttribute be added. First of all it would be called unitProperty. Secondly, the schema that have been released on hedxml can not be changed. They will be in the old format. They will also not have unitProperty. This will be up through HED8.0.0-alpha.2. I am assuming that there will be a cutoff of versions?

Sorry, `unitAttribute` was a typo. The code has the correct `unitProperty` name. The new parser will only run on base schemas with version 8.0.0-alpha.3 or greater. I still haven't determined how it will figure out parsing for library schemas. I suppose it would check for a library attribute and assume they all use the new spec.

**Comment by VisLab** [comment]
All library schemas must be in the new format.  This seems to be okay with me.  I have made the change in the alpha.3 schema to add unitProperty.  I will add to the spec.

**Comment by VisLab** [comment]
I have added to the spec.  Let me know if it is consistent or anything needs to be changed.

**Comment by happy5214** [comment]
> I have added to the spec. Let me know if it is consistent or anything needs to be changed.

The `unitProperty` tags didn't make it into the alpha.3 XML. I had to add them manually.

**Comment by happy5214** [comment]
> > I have added to the spec. Let me know if it is consistent or anything needs to be changed.
> 
> The `unitProperty` tags didn't make it into the alpha.3 XML. I had to add them manually.

The actual attribute tags aren't on the units themselves either. I could not run unit tests on this schema.

**Comment by happy5214** [comment]
I used an old copy of the alpha.3 schema, which caused the new schema parsing tests (which count the number of instances of certain attributes in the _new_ version) to fail. They should resolve once I put the fixed version back in.

**Comment by VisLab** [comment]
I think the new version for alpha.3 is on hedxml-test.  Could you verify and then merge if it is okay. Otherwise let us know if there is an issue with the new format.

**Comment by happy5214** [comment]
It's already the latest XML as of this post. I'll go ahead and merge.

**Pull request merged**
