### PR TITLE
Rewrite of tokenizer and introduction of object-based test cases

### PR DESCRIPTION
**Pull request by VisLab**
This PR represents a rewrite of the tokenizer, which is the syntax parser for hedstrings. The tokenizer now catches errors from bad slashes and blanks in addition to errors caught in the previous parser.  An object based data framework for the test cases was introduced to make it easy to add testcases for the tokenizer. 

A start was also made on converting the bids.spec tests to the object framework for clearer description of what was being tested and for possible porting to the Python validator for test cases.

### CODE REVIEW

**Comment by VisLab** [comment]
@happy5214 I have updated and moved the converter tests to the tests directory. I am going to go ahead and merge to the develop branch. I also corrected a bug in the `tokenizer`. 

In the next PR, I am going to convert some more of the `bids.spec` tests to `bidsTests.spec` and make a first pass at converting the `events.spec` to the separated test format. Eventually, we may be able to pull out some of the common functions to a test utilities, but I don't think we should worry about that yet.

**Comment by VisLab** [comment]
@happy5214 Could you please review --- I think this should be merged with develop and soon with master.

Summary:
1.  The main changes are organizational.  I started to convert the existing test to tests based on separate datafiles that could easily be ported to use as tests for the python tools.  This is a big job and will take some time.  The datafiles are now in `tests/testData`
2.  There were two `converters.js` files.  I renamed one of them to be `tagConverter.js` and moved it to the `parser` directory.
3. I moved all of the `.spec.js` files that were scattered in the code to the `tests` subdirectory.
4. I corrected a bug in the `tokenizer` -- it wasn't properly detecting slash after open parenthesis.
5. I corrected a bug in the column splicer --- it was crashing when `{HED}` was used as a splice but there was not `HED` column in the tsv.file.

**Comment by VisLab** [comment]
Revised the PR to not treat a missing HED column in tsv as an error when {HED} is used.

**Review by happy5214 — APPROVED** [review]

**Comment by happy5214** [comment]
We walked through these changes during a Zoom meeting.

**Pull request merged**
